theme: jekyll-theme-minimal
title: "Dania Bawab's Homepage"
description: |
  DATASET - Development Assistance for Health Database 1990-2025 (https://ghdx.healthdata.org/record/ihme-data/development-assistance-health-database-1990-2025).
  This dataset is vital for the improvement of fund disbursements in healthcare. The analysis of this dataset can help decide which communities, regions, or health areas to prioritize with funding. This dataset can also show how these fundings are being used and how they are impacting the designated community/region.

  BOOK - A Course in Machine Learning by Hal Daumé III (http://ciml.info/).
  This book is interesting to me because I am currently looking to improve and advance my skills in machine learning. This is a free book, yet it has so much information on machine learning—from definitions to different techniques and processes. This seems to be a good book for it, and I am excited to go through it more.
